#!/usr/bin/env bash
# Copyright 2009-2017 Ram Rachum.
# This program is distributed under the MIT license.

set -e

if [[ $1 =~ ^[1-9][0-9]*$ ]] ; then
    if [ $1 -gt 20 ] ; then
        echo "Error: Can't specify a depth bigger than 20, please specify ref directly." >&2
    exit 1
    fi
    commit_to_amend=$(git rev-parse --verify HEAD~$1)
else
    commit_to_amend=$(git rev-parse --verify $1)
fi

if (git diff --cached --quiet) ; then # If nothing is staged
    git add --all
else
    echo "You have staged changes. git past-amend requires the changes you'll be adding to not be staged, to avoid a situation where some stages are changed and some aren't, since git past-amend isn't smart enough to use only the ones you staged and leave the ones you didn't." >&2
    exit 1
fi

if (git diff --cached --quiet) ; then # If nothing is staged
    echo "There are no changes." >&2
    exit 1
fi

git stash save
git checkout $commit_to_amend --detach
git stash pop
git add --all
git commit --amend --no-edit
rebase_target=$(git rev-parse --verify HEAD)
git checkout -
git rebase $rebase_target
    
