#!/usr/bin/env bash
# Copyright 2009-2017 Ram Rachum.
# This program is distributed under the MIT license.

set -e

if ! [[ $1 =~ ^[1-9][0-9]*$ ]] ; then
   echo "Error: Argument must be an integer bigger than 0." >&2
   exit 1
fi

depth=$1

if (git diff --cached --quiet) ; then # If nothing is staged
    git add --all
else
    echo "You have staged changes. git past-amend requires the changes you'll be adding to not be staged, to avoid a situation where some stages are changed and some aren't, since git past-amend isn't smart enough to use only the ones you staged and leave the ones you didn't." >&2
    exit 1
fi

if (git diff --cached --quiet) ; then # If nothing is staged
    echo "There are no changes." >&2
    exit 1
fi

git stash save
git checkout HEAD~$depth
git stash pop
git add --all
git commit --amend --no-edit
rebase_target=$(git rev-parse --verify HEAD)
git checkout - 
git rebase $rebase_target
    
